import "./globals.css";
import { Barlow, Montserrat } from "next/font/google";
import Popover from "./components/Popover";

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${barlow.variable} ${montserrat.variable}`}>
      <body className="min-h-full flex flex-col">
        {children}
        <Popover />
      </body>
    </html>
  );
}
